server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  flyway:
    baseline-on-migrate: true

vetclinic:
  bootstrap:
    enabled: ${VETCLINIC_BOOTSTRAP_ENABLED:false}
    admin-username: ${VETCLINIC_BOOTSTRAP_ADMIN_USERNAME:admin}
    admin-password: ${VETCLINIC_BOOTSTRAP_ADMIN_PASSWORD:}
